#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '------PRE-COMMIT HOOK START------'
echo 'Running pre commit hook by Nemo the Sensei'

# Check if the code needs formatting
if ! dotnet format --verify-no-changes; then
  echo 'Code needs formatting. Running format...'
  dotnet format
  git add .
  git commit -m "Formatted code by pre-commit hook"
fi

# Build and test the project
dotnet build
dotnet test

echo 'Pre-commit hook executed successfully - Thanks Nemo'
echo '------PRE-COMMIT HOOK END------'
